Repository DLR-SC/Overtarget, pull requests merged in 2020-01, with the labels that each got.

#36 Feature/task 35 checkstyle definition
  checkStyle/checkStylesDefinition.xml
  de.dlr.sc.overtarget.language/src/de/dlr/sc/overtarget/language/scoping/OvertargetScopeProvider.xtend
  de.dlr.sc.overtarget.language/xtend-gen/de/dlr/sc/overtarget/language/scoping/OvertargetScopeProvider.java
  maven/pom.xml
Labels: easy

#42 Change URI to Maven repository - (Task #41)
  build.xml
Labels: build

#40 Changed gta to gtk - (Task #39)
  de.dlr.sc.overtarget.language.ide/src-gen/de/dlr/sc/overtarget/language/ide/contentassist/antlr/internal/InternalOvertarget.g
  de.dlr.sc.overtarget.language.ide/src-gen/de/dlr/sc/overtarget/language/ide/contentassist/antlr/internal/InternalOvertarget.tokens
  de.dlr.sc.overtarget.language.ide/src-gen/de/dlr/sc/overtarget/language/ide/contentassist/antlr/internal/InternalOvertargetLexer.java
  de.dlr.sc.overtarget.language.ide/src-gen/de/dlr/sc/overtarget/language/ide/contentassist/antlr/internal/InternalOvertargetParser.java
  de.dlr.sc.overtarget.language/src-gen/de/dlr/sc/overtarget/language/parser/antlr/internal/InternalOvertarget.g
  de.dlr.sc.overtarget.language/src-gen/de/dlr/sc/overtarget/language/parser/antlr/internal/InternalOvertarget.tokens
  de.dlr.sc.overtarget.language/src-gen/de/dlr/sc/overtarget/language/parser/antlr/internal/InternalOvertargetLexer.java
  de.dlr.sc.overtarget.language/src-gen/de/dlr/sc/overtarget/language/parser/antlr/internal/InternalOvertargetParser.java
  de.dlr.sc.overtarget.language/src-gen/de/dlr/sc/overtarget/language/services/OvertargetGrammarAccess.java
  de.dlr.sc.overtarget.language/src/de/dlr/sc/overtarget/language/TargetModel.xtext
Labels: bug, easy

#34 Update and improve build pipeline
  .travis.yml
  checkStyle/checkStylesDefinition.xml
  de.dlr.sc.overtarget.language.tests/src/de/dlr/sc/overtarget/language/tests/AllTests.java
  de.dlr.sc.overtarget.language.tests/src/de/dlr/sc/overtarget/language/tests/OvertargetOutputConfigurationProviderTest.java
  de.dlr.sc.overtarget.language.tests/xtend-gen/de/dlr/sc/overtarget/language/tests/OvertargetParsingTest.java
  de.dlr.sc.overtarget.language.ui/src/de/dlr/sc/overtarget/language/ui/handler/VersionHandler.java
  de.dlr.sc.overtarget.language/src/de/dlr/sc/overtarget/language/Activator.java
  de.dlr.sc.overtarget.language/src/de/dlr/sc/overtarget/language/generator/OvertargetOutputConfigurationProvider.java
  de.dlr.sc.overtarget.language/src/de/dlr/sc/overtarget/language/util/VersionHandlerHelper.java
  de.dlr.sc.overtarget.language/src/de/dlr/sc/overtarget/language/validation/ValidatorHelper.java
  de.dlr.sc.overtarget.language/xtend-gen/de/dlr/sc/overtarget/language/generator/OvertargetGenerator.java
  maven/pom.xml
Labels: build

#48 Improve security on CI deployment
  .travis.yml
  bash/ssh-add-password
  id_ed25519.enc
Labels: build, feature
